const UserActionTypes = {
  LOAD_USER_START: "LOAD_USER_START",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
  SET_USER_EMPTY: "SET_USER_EMPTY",
  SET_ERROR_MSG_EMPTY: "SET_ERROR_MSG_EMPTY",
  SET_EDIT_USER: "SET_EDIT_USER",
  //Edit user
  // LOAD_EDIT_USER_START: "LOAD_EDIT_USER_START",
  // LOAD_EDIT_USER_SUCESS: "LOAD_EDIT_USER_SUCESS",
  // LOAD_EDIT_USER_FAIL: "LOAD_EDIT_USER_FAIL",
}

export default UserActionTypes;